name: story
description: Instagram stories like UI with rich animations and customizability.
version: 1.1.0
homepage: https://github.com/santa112358/story

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

